blank_issues_enabled: false
contact_links:
  - name: Docs Contributor Code of Conduct
  - url: https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md
  - about: Please use this as a reference while working on/ submitting issues.
