name: Post-Merge Survey
on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed]
jobs:
  run:
    if: >-
      github.event.pull_request.user.login != 'Dusch4593' &&
      github.event.pull_request.user.login != 'yangc95' &&
      github.event.pull_request.user.login != 'KTom101' &&
      github.event.pull_request.user.login != 'SSwiniarski' &&
      github.event.pull_request.user.login != 'HishamT' &&
      github.event.pull_request.user.login != 'caupolicandiaz' &&
      github.event.pull_request.user.login != 'lucwhite'
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestMerged: |
            ðŸ‘‹ @{{ author }}
            You have contributed to Codecademy Docs, and we would like to know more about you and your experience.
            Please take a minute to fill out [this four question survey](https://codecademyready.typeform.com/to/O3hzYoBB) to help us better understand Docs contributions and how we can improve the experience for you and our learners.
            Thank you for your help!
          issuesClosed: |
            ðŸŒ¸ Thanks for closing this Issue!
            Please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs, or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
