name: Push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v1
        with:
          command: ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ["compile", "format:verify", "lint:js", "lint:md", "test"]

on:
  push:
    branches:
      - main
      - dev-test
  pull_request:
