name: Push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v2.0.0
        with:
          command: ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ['compile', 'format:verify', 'lint:js', 'lint:md', 'test']

on:
  push:
    branches:
      - main
  pull_request:
